services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost --user=${MYSQL_USER} --password=${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s 

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: db 
      MYSQL_PORT: 3306
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./back:/app/back
      - /app/back/target

  frontend:
    build:
      context: ./frontend
    working_dir: /app/frontend
    command: sh -c "npm run start || npm run dev"
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      backend:
        condition: service_started
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules

volumes:
  db_data:
  backend_data:
